name: 'Report Bug'
description: "Report a bug that does not abruptly end a game session or prevent the start of the game."
type: bug
body:
  - type: input
    id: version
    attributes:
      label: Pack Version
      description: Have you checked that the version you are playing is up-to-date before reporting? In some cases, a newer version may have been released, and the bug you are reporting may have been resolved.
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: input
    id: log
    attributes:
      label: Error Log
      description: Please provide a link to the error log. I recommend [https://mclo.gs/](https://mclo.gs/)
      placeholder: "https://mclo.gs/xxxxxxxx"
  - type: dropdown
    id: playmode
    attributes:
      label: SinglePlay or Server?
      description: How are you playing with this modpack?
      options:
      - Single Player
      - Multi Player
      - Docker
      - Other
      - "Don't know"
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Your Expectation
      description: What did you try to do, and what did you expect to happen? Attach screenshots if needed.
      placeholder: "Example: Trying to craft Foo. Expect to consume 1 Bar and get 1 Foo."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: The Reality
      description: What happened instead? Attach screenshots if needed.
      placeholder: "Example: 1 Foo is crafted but no Bar is consumed."
    validations:
      required: true
