name: Report issues
title: "[Other]"
description: "What else do you have? What do you want me to say?"
labels:
  - "others"
body:
  - type: textarea
    id: say
    attributes:
      label: Say
      description: Is this a bug or a suggestion about Modpack? Then what were you thinking when you posted this?
    validations:
      required: true
