blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/tier940
    about: >-
      You can send me a message or use the [#GTExpert](https://twitter.com/hashtag/GTExpert) hashtag.
  # - name: Discord
  #   about: >-
  #     I haven't thought about it yet, but if it's going to be a smooth process or something, I might make it.
