blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/tier940
    about: >-
      You can send me a message or use the #GTExpert hashtag.
  - name: Discord
    url: https://discord.gg/xBwHpZyZdW
    about: >-
      Please ask questions in the #bugs-because-i-m-a-dummy channel of this discord server.
