name: Build Setup
description: Setup for standard Python build

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      shell: bash
      run: pip install uv

    - name: Setup Python Cache 
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      shell: bash
      run: uv pip install --system -r ./buildtools/requirements.txt
