name: Build Setup
description: Setup for standard Python build

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y zip jq wget

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version-file: ./buildtools/pyproject.toml

    - name: Install dependencies
      shell: bash
      working-directory: ./buildtools
      run: uv sync
