on:
  push:
    paths:
    - 'release/v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run test action
      id: test_action
      uses: itsmeow/curseforge-upload@master
      with:
        token: ${{ secrets.CF_API_TOKEN }}
        project_id: 262222
        game_endpoint: minecraft
        file_path: test_jar.jar
        changelog: Test changelog message!
        display_name: Test Jar
        game_versions: minecraft-1-12:1.12.2,4458,2:Java 7,Minecraft 1.12:1-12,1.12.1,Forge
        release_type: alpha
        relations: betteranimalsplus:incompatible,claimit:optionalDependency
